// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Insertable, Selectable, Updateable } from "kysely"
import type { IndexedPackagesId } from "./IndexedPackages"

/** Identifier type for public.indexed_package_skills */
export type IndexedPackageSkillsId = number & { __brand: "public.indexed_package_skills" }

/** Represents the table public.indexed_package_skills */
export default interface IndexedPackageSkillsTable {
	id: ColumnType<
		IndexedPackageSkillsId,
		IndexedPackageSkillsId | undefined,
		IndexedPackageSkillsId
	>

	indexed_package_id: ColumnType<
		IndexedPackagesId,
		IndexedPackagesId,
		IndexedPackagesId
	>

	name: ColumnType<string, string, string>

	description: ColumnType<string | null, string | null, string | null>

	relative_path: ColumnType<string, string, string>
}

export type IndexedPackageSkills = Selectable<IndexedPackageSkillsTable>

export type NewIndexedPackageSkills = Insertable<IndexedPackageSkillsTable>

export type IndexedPackageSkillsUpdate = Updateable<IndexedPackageSkillsTable>
