// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Insertable, Selectable, Updateable } from "kysely"

/** Identifier type for public.indexed_packages */
export type IndexedPackagesId = number & { __brand: "public.indexed_packages" }

/** Represents the table public.indexed_packages */
export default interface IndexedPackagesTable {
	id: ColumnType<IndexedPackagesId, IndexedPackagesId | undefined, IndexedPackagesId>

	gh_repo: ColumnType<string, string, string>

	declaration: ColumnType<string, string, string>

	path: ColumnType<string | null, string | null, string | null>

	name: ColumnType<string | null, string | null, string | null>

	description: ColumnType<string | null, string | null, string | null>

	gh_owner: ColumnType<string, string, string>

	gh_stars: ColumnType<number, number, number>

	gh_description: ColumnType<string | null, string | null, string | null>

	gh_topics: ColumnType<string[], string[], string[]>

	gh_license: ColumnType<string | null, string | null, string | null>

	gh_language: ColumnType<string | null, string | null, string | null>

	gh_updated_at: ColumnType<Date, Date | string, Date | string>

	discovered_at: ColumnType<Date, Date | string | undefined, Date | string>

	updated_at: ColumnType<Date, Date | string | undefined, Date | string>
}

export type IndexedPackages = Selectable<IndexedPackagesTable>

export type NewIndexedPackages = Insertable<IndexedPackagesTable>

export type IndexedPackagesUpdate = Updateable<IndexedPackagesTable>
